import { useState, useRef, useEffect } from "react";
import { useQuery, useMutation } from "@tanstack/react-query";
import { queryClient } from "@/lib/queryClient";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Skeleton } from "@/components/ui/skeleton";
import { ScrollArea } from "@/components/ui/scroll-area";
import { Send, Bot, User, Sparkles, Plus, Trash2, MessageSquare, ArrowLeft, Download, Loader2 } from "lucide-react";
import { Link } from "wouter";
import { useToast } from "@/hooks/use-toast";

interface ChatMessage {
  id?: number;
  role: "user" | "assistant";
  content: string;
}

interface ConversationData {
  id: number;
  title: string;
  messages?: ChatMessage[];
}

function hasPicksContent(content: string): boolean {
  return (content.includes("Pick:") || content.includes("Best Pick:") || content.includes("picks")) &&
    (content.includes("vs") || content.includes("VS")) &&
    content.includes("%");
}

function roundRect(ctx: CanvasRenderingContext2D, x: number, y: number, w: number, h: number, r: number) {
  ctx.beginPath();
  ctx.moveTo(x + r, y);
  ctx.lineTo(x + w - r, y);
  ctx.quadraticCurveTo(x + w, y, x + w, y + r);
  ctx.lineTo(x + w, y + h - r);
  ctx.quadraticCurveTo(x + w, y + h, x + w - r, y + h);
  ctx.lineTo(x + r, y + h);
  ctx.quadraticCurveTo(x, y + h, x, y + h - r);
  ctx.lineTo(x, y + r);
  ctx.quadraticCurveTo(x, y, x + r, y);
  ctx.closePath();
}

function drawChatPicksToCanvas(content: string): HTMLCanvasElement {
  const canvas = document.createElement("canvas");
  const scale = 2;
  const width = 400;
  const padding = 24;
  const lineHeight = 18;

  const lines = content.split("\n").filter(l => l.trim());
  const totalHeight = padding * 2 + 50 + lines.length * lineHeight + 40;

  canvas.width = width * scale;
  canvas.height = totalHeight * scale;
  const ctx = canvas.getContext("2d")!;
  ctx.scale(scale, scale);

  ctx.fillStyle = "#0a0e27";
  ctx.fillRect(0, 0, width, totalHeight);

  let y = padding;

  ctx.fillStyle = "#00FFA3";
  ctx.font = "bold 16px Inter, system-ui, sans-serif";
  ctx.fillText("★", padding, y + 18);
  ctx.fillStyle = "#ffffff";
  ctx.font = "bold 15px Inter, system-ui, sans-serif";
  ctx.fillText("OddsAura AI Picks", padding + 22, y + 17);
  y += 30;

  ctx.strokeStyle = "rgba(0,255,163,0.3)";
  ctx.lineWidth = 1;
  ctx.beginPath();
  ctx.moveTo(padding, y);
  ctx.lineTo(width - padding, y);
  ctx.stroke();
  y += 16;

  for (const line of lines) {
    const clean = line.replace(/\*\*/g, "").replace(/---/g, "").trim();
    if (!clean) continue;

    const isHeader = line.includes("**") && (line.includes("vs") || line.includes("Summary") || line.includes("Odds") || line.includes("Return") || line.includes("picks"));
    const isPick = clean.startsWith("Pick:") || clean.includes("Pick:");
    const isStat = clean.includes("Combined Odds") || clean.includes("Potential Return") || clean.includes("Betslip");

    if (isHeader) {
      ctx.fillStyle = "#ffffff";
      ctx.font = "bold 12px Inter, system-ui, sans-serif";
    } else if (isPick) {
      ctx.fillStyle = "#00FFA3";
      ctx.font = "600 11px Inter, system-ui, sans-serif";
    } else if (isStat) {
      ctx.fillStyle = "#FFB800";
      ctx.font = "bold 11px 'Roboto Mono', monospace";
    } else {
      ctx.fillStyle = "rgba(255,255,255,0.6)";
      ctx.font = "11px Inter, system-ui, sans-serif";
    }

    const maxWidth = width - padding * 2;
    let text = clean;
    if (ctx.measureText(text).width > maxWidth) {
      while (ctx.measureText(text + "...").width > maxWidth && text.length > 0) {
        text = text.slice(0, -1);
      }
      text += "...";
    }

    ctx.fillText(text, padding, y);
    y += lineHeight;
  }

  y += 8;
  ctx.fillStyle = "rgba(255,255,255,0.2)";
  ctx.font = "8px Inter, system-ui, sans-serif";
  const dateText = "Generated by OddsAura AI - " + new Date().toLocaleDateString();
  const dateWidth = ctx.measureText(dateText).width;
  ctx.fillText(dateText, (width - dateWidth) / 2, y + 10);

  return canvas;
}

export default function AIChat() {
  const [input, setInput] = useState("");
  const [activeConversation, setActiveConversation] = useState<number | null>(null);
  const [streamingContent, setStreamingContent] = useState("");
  const [isStreaming, setIsStreaming] = useState(false);
  const [localMessages, setLocalMessages] = useState<ChatMessage[]>([]);
  const [savingImage, setSavingImage] = useState<number | null>(null);
  const messagesEndRef = useRef<HTMLDivElement>(null);
  const inputRef = useRef<HTMLTextAreaElement>(null);
  const { toast } = useToast();

  const { data: conversations, isLoading: convLoading } = useQuery<ConversationData[]>({
    queryKey: ["/api/conversations"],
  });

  const { data: activeConv } = useQuery<ConversationData>({
    queryKey: ["/api/conversations", activeConversation],
    enabled: !!activeConversation,
  });

  const createConversation = useMutation({
    mutationFn: async () => {
      const res = await fetch("/api/conversations", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ title: "New Chat" }),
      });
      return res.json();
    },
    onSuccess: (data: ConversationData) => {
      setActiveConversation(data.id);
      setLocalMessages([]);
      queryClient.invalidateQueries({ queryKey: ["/api/conversations"] });
    },
  });

  const deleteConversation = useMutation({
    mutationFn: async (id: number) => {
      await fetch(`/api/conversations/${id}`, { method: "DELETE" });
    },
    onSuccess: () => {
      setActiveConversation(null);
      setLocalMessages([]);
      queryClient.invalidateQueries({ queryKey: ["/api/conversations"] });
    },
  });

  useEffect(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: "smooth" });
  }, [activeConv?.messages, streamingContent, localMessages]);

  useEffect(() => {
    if (activeConv?.messages) {
      setLocalMessages([]);
    }
  }, [activeConv?.messages]);

  const handleSend = async () => {
    if (!input.trim() || isStreaming) return;

    let convId = activeConversation;
    if (!convId) {
      const res = await fetch("/api/conversations", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ title: input.slice(0, 50) }),
      });
      const conv = await res.json();
      convId = conv.id;
      setActiveConversation(conv.id);
      queryClient.invalidateQueries({ queryKey: ["/api/conversations"] });
    }

    const userMessage = input.trim();
    setInput("");
    setIsStreaming(true);
    setStreamingContent("");
    setLocalMessages(prev => [...prev, { role: "user", content: userMessage }]);

    try {
      const response = await fetch(`/api/conversations/${convId}/messages`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ content: userMessage }),
      });

      if (!response.ok) {
        throw new Error(`HTTP ${response.status}`);
      }

      const reader = response.body?.getReader();
      if (!reader) {
        throw new Error("No response body");
      }

      const decoder = new TextDecoder();
      let fullContent = "";

      while (true) {
        const { done, value } = await reader.read();
        if (done) break;

        const chunk = decoder.decode(value, { stream: true });
        const lines = chunk.split("\n");

        for (const line of lines) {
          if (!line.startsWith("data: ")) continue;
          try {
            const data = JSON.parse(line.slice(6));
            if (data.content) {
              fullContent += data.content;
              setStreamingContent(fullContent);
            }
            if (data.done) {
              setIsStreaming(false);
              setStreamingContent("");
              setLocalMessages([]);
              queryClient.invalidateQueries({ queryKey: ["/api/conversations", convId] });
              queryClient.invalidateQueries({ queryKey: ["/api/conversations"] });
            }
            if (data.error) {
              setIsStreaming(false);
              setStreamingContent("");
              setLocalMessages(prev => [...prev, { role: "assistant", content: "Sorry, I encountered an error. Please try again." }]);
            }
          } catch {}
        }
      }
    } catch (error) {
      console.error("Chat error:", error);
      setIsStreaming(false);
      setStreamingContent("");
      setLocalMessages(prev => [...prev, { role: "assistant", content: "Failed to connect. Please try again." }]);
    }
  };

  const handleKeyDown = (e: React.KeyboardEvent) => {
    if (e.key === "Enter" && !e.shiftKey) {
      e.preventDefault();
      handleSend();
    }
  };

  const handleSavePicksImage = async (content: string, index: number) => {
    setSavingImage(index);
    try {
      const canvas = drawChatPicksToCanvas(content);
      const filename = `oddsaura-picks-${new Date().toISOString().split("T")[0]}.png`;

      try {
        const blob = await new Promise<Blob>((resolve, reject) => {
          canvas.toBlob(b => b ? resolve(b) : reject(new Error("toBlob failed")), "image/png");
        });

        if (navigator.share && /mobile|android|iphone/i.test(navigator.userAgent)) {
          const file = new File([blob], filename, { type: "image/png" });
          await navigator.share({ files: [file], title: "OddsAura Picks" });
        } else {
          const url = URL.createObjectURL(blob);
          const a = document.createElement("a");
          a.href = url;
          a.download = filename;
          document.body.appendChild(a);
          a.click();
          document.body.removeChild(a);
          setTimeout(() => URL.revokeObjectURL(url), 5000);
        }
      } catch {
        const dataUrl = canvas.toDataURL("image/png");
        const w = window.open();
        if (w) {
          w.document.write(`<img src="${dataUrl}" style="max-width:100%" />`);
          w.document.title = "OddsAura Picks - Right click to save";
        }
      }

      toast({ title: "Picks saved!", description: "Your picks image has been downloaded." });
    } catch (err) {
      console.error("Failed to save picks image:", err);
      toast({ title: "Save failed", description: "Could not save image. Please try again.", variant: "destructive" });
    } finally {
      setSavingImage(null);
    }
  };

  const serverMessages = activeConv?.messages || [];
  const displayMessages: ChatMessage[] = [
    ...serverMessages,
    ...localMessages,
    ...(streamingContent ? [{ role: "assistant" as const, content: streamingContent }] : []),
  ];

  return (
    <div className="h-full flex flex-col md:flex-row">
      <div className="w-full md:w-64 border-b md:border-b-0 md:border-r border-[#00FFA3]/10 flex-col hidden md:flex bg-black/20">
        <div className="p-3 border-b border-[#00FFA3]/10 flex gap-2">
          <Link href="/">
            <Button size="icon" variant="ghost" className="text-white/60 hover:text-white md:hidden" data-testid="button-back-chat">
              <ArrowLeft className="w-4 h-4" />
            </Button>
          </Link>
          <Button
            variant="outline"
            className="flex-1 gap-2 border-[#00FFA3]/20 text-white hover:bg-[#00FFA3]/10 hover:text-[#00FFA3]"
            onClick={() => createConversation.mutate()}
            data-testid="button-new-chat"
          >
            <Plus className="w-4 h-4" />
            New Chat
          </Button>
        </div>
        <ScrollArea className="flex-1 p-2">
          {convLoading ? (
            <div className="space-y-2">
              {[...Array(3)].map((_, i) => <Skeleton key={i} className="h-10 rounded-md" />)}
            </div>
          ) : conversations && conversations.length > 0 ? (
            <div className="space-y-1">
              {conversations.map((conv) => (
                <div
                  key={conv.id}
                  className={`flex items-center gap-2 p-2 rounded-md cursor-pointer transition-colors group ${
                    activeConversation === conv.id ? "bg-[#00FFA3]/10 text-[#00FFA3]" : "text-white/50 hover:text-white hover:bg-white/5"
                  }`}
                  onClick={() => setActiveConversation(conv.id)}
                  data-testid={`conversation-item-${conv.id}`}
                >
                  <MessageSquare className="w-4 h-4 flex-shrink-0" />
                  <span className="text-sm truncate flex-1">{conv.title}</span>
                  <button
                    className="opacity-0 group-hover:opacity-100 transition-opacity"
                    onClick={(e) => {
                      e.stopPropagation();
                      deleteConversation.mutate(conv.id);
                    }}
                    data-testid={`button-delete-conversation-${conv.id}`}
                  >
                    <Trash2 className="w-3.5 h-3.5 text-red-400" />
                  </button>
                </div>
              ))}
            </div>
          ) : (
            <p className="text-xs text-white/30 text-center p-4">No conversations yet</p>
          )}
        </ScrollArea>
      </div>

      <div className="flex-1 flex flex-col min-h-0">
        <div className="flex items-center gap-2 p-3 border-b border-[#00FFA3]/10 md:hidden">
          <Link href="/">
            <Button size="icon" variant="ghost" className="text-white/60 hover:text-white" data-testid="button-back-chat-mobile">
              <ArrowLeft className="w-4 h-4" />
            </Button>
          </Link>
          <span className="text-sm font-display font-bold text-white">AI Advisor</span>
          <div className="flex-1" />
          <Button
            variant="outline"
            size="sm"
            className="gap-1 border-[#00FFA3]/20 text-white hover:bg-[#00FFA3]/10 hover:text-[#00FFA3] text-xs"
            onClick={() => createConversation.mutate()}
            data-testid="button-new-chat-mobile"
          >
            <Plus className="w-3 h-3" />
            New
          </Button>
        </div>
        {displayMessages.length === 0 && !isStreaming ? (
          <div className="flex-1 flex items-center justify-center p-6">
            <div className="text-center max-w-md">
              <div className="w-16 h-16 rounded-full bg-[#00FFA3]/10 border border-[#00FFA3]/20 flex items-center justify-center mx-auto mb-6">
                <Sparkles className="w-8 h-8 text-[#00FFA3]" />
              </div>
              <h2 className="text-xl font-display font-bold text-white mb-3" data-testid="text-chat-welcome">
                AI Advisor
              </h2>
              <p className="text-sm text-white/50 leading-relaxed mb-6">
                Ask about match predictions, team form, betting strategies, odds analysis, and more. I analyze real-time football data to provide intelligent insights.
              </p>
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-2">
                {[
                  "Best bets for today's Premier League matches?",
                  "Analyze Arsenal vs Chelsea head-to-head",
                  "Which BTTS picks have highest confidence?",
                  "Give me 3 value bets for this weekend",
                ].map((prompt, i) => (
                  <button
                    key={i}
                    className="p-3 rounded-md border border-white/10 bg-white/5 text-left text-xs text-white/60 transition-colors hover:bg-[#00FFA3]/5 hover:border-[#00FFA3]/20 hover:text-white"
                    onClick={() => {
                      setInput(prompt);
                      inputRef.current?.focus();
                    }}
                    data-testid={`button-suggestion-${i}`}
                  >
                    {prompt}
                  </button>
                ))}
              </div>
            </div>
          </div>
        ) : (
          <ScrollArea className="flex-1 p-4">
            <div className="max-w-3xl mx-auto space-y-4">
              {displayMessages.map((msg, i) => (
                <div key={i} className={`flex gap-3 ${msg.role === "user" ? "justify-end" : "justify-start"}`}>
                  {msg.role === "assistant" && (
                    <div className="w-8 h-8 rounded-full bg-[#00FFA3]/10 border border-[#00FFA3]/20 flex items-center justify-center flex-shrink-0">
                      <Bot className="w-4 h-4 text-[#00FFA3]" />
                    </div>
                  )}
                  <div
                    className={`max-w-[80%] p-3 rounded-lg text-sm leading-relaxed ${
                      msg.role === "user"
                        ? "bg-[#00FFA3] text-black font-medium"
                        : "bg-white/5 border border-white/10 text-white"
                    }`}
                    data-testid={`message-${msg.role}-${i}`}
                  >
                    <div className="whitespace-pre-wrap">{msg.content}</div>
                    {isStreaming && i === displayMessages.length - 1 && msg.role === "assistant" && (
                      <span className="inline-block w-1.5 h-4 bg-[#00FFA3] animate-pulse ml-1" />
                    )}
                    {msg.role === "assistant" && !isStreaming && hasPicksContent(msg.content) && (
                      <button
                        onClick={() => handleSavePicksImage(msg.content, i)}
                        disabled={savingImage === i}
                        className="mt-2 flex items-center gap-1.5 px-3 py-1.5 rounded-md bg-[#00FFA3]/10 border border-[#00FFA3]/20 text-[#00FFA3] text-xs font-medium hover:bg-[#00FFA3]/20 transition-colors disabled:opacity-50"
                      >
                        {savingImage === i ? (
                          <Loader2 className="w-3 h-3 animate-spin" />
                        ) : (
                          <Download className="w-3 h-3" />
                        )}
                        {savingImage === i ? "Saving..." : "Save Picks as Image"}
                      </button>
                    )}
                  </div>
                  {msg.role === "user" && (
                    <div className="w-8 h-8 rounded-full bg-white/10 border border-white/10 flex items-center justify-center flex-shrink-0">
                      <User className="w-4 h-4 text-white" />
                    </div>
                  )}
                </div>
              ))}
              <div ref={messagesEndRef} />
            </div>
          </ScrollArea>
        )}

        <div className="p-4 border-t border-[#00FFA3]/10">
          <div className="max-w-3xl mx-auto flex gap-2">
            <textarea
              ref={inputRef}
              value={input}
              onChange={(e) => setInput(e.target.value)}
              onKeyDown={handleKeyDown}
              placeholder="Ask about match predictions, betting strategies, team analysis..."
              className="flex-1 resize-none rounded-lg border border-white/15 bg-white/5 px-4 py-3 text-sm text-white placeholder:text-white/30 focus:outline-none focus:ring-1 focus:ring-[#00FFA3] min-h-[44px] max-h-[120px]"
              rows={1}
              disabled={isStreaming}
              data-testid="input-chat-message"
            />
            <Button
              size="icon"
              onClick={handleSend}
              disabled={!input.trim() || isStreaming}
              className="bg-[#00FFA3] text-black hover:bg-[#00FFA3]/80"
              data-testid="button-send-message"
            >
              <Send className="w-4 h-4" />
            </Button>
          </div>
        </div>
      </div>
    </div>
  );
}
