import { useCallback, useState } from "react";
import { useBetSlip } from "@/lib/bet-slip-context";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { ScrollArea } from "@/components/ui/scroll-area";
import { X, Trash2, Star, TrendingUp, Download, Check, Loader2, Share2, Link as LinkIcon } from "lucide-react";
import { apiRequest } from "@/lib/queryClient";
import { useToast } from "@/hooks/use-toast";

function drawPicksToCanvas(
  groupedMatches: { matchId: number; homeTeam: string; awayTeam: string; competition: string; picks: { market: string; pick: string; confidence: number }[] }[],
  itemCount: number,
  combinedConfidence: number
): HTMLCanvasElement {
  const canvas = document.createElement("canvas");
  const scale = 2;
  const width = 360;
  const padding = 20;
  const contentWidth = width - padding * 2;

  let totalHeight = padding;
  totalHeight += 40;
  totalHeight += 16;

  for (const group of groupedMatches) {
    totalHeight += 50;
    totalHeight += group.picks.length * 44;
    totalHeight += 16;
  }

  totalHeight += 50;
  totalHeight += 30;
  totalHeight += padding;

  canvas.width = width * scale;
  canvas.height = totalHeight * scale;
  const ctx = canvas.getContext("2d")!;
  ctx.scale(scale, scale);

  ctx.fillStyle = "#0a0e27";
  ctx.fillRect(0, 0, width, totalHeight);

  let y = padding;

  ctx.fillStyle = "#00FFA3";
  ctx.font = "bold 16px Inter, system-ui, sans-serif";
  ctx.fillText("★", padding, y + 18);
  ctx.fillStyle = "#ffffff";
  ctx.font = "bold 15px Inter, system-ui, sans-serif";
  ctx.fillText("My Picks - OddsAura", padding + 22, y + 17);
  y += 28;

  ctx.strokeStyle = "rgba(0,255,163,0.2)";
  ctx.lineWidth = 1;
  ctx.beginPath();
  ctx.moveTo(padding, y);
  ctx.lineTo(width - padding, y);
  ctx.stroke();
  y += 16;

  for (const group of groupedMatches) {
    ctx.fillStyle = "rgba(255,255,255,0.04)";
    const groupHeight = 42 + group.picks.length * 44;
    roundRect(ctx, padding, y, contentWidth, groupHeight, 8);
    ctx.fill();
    ctx.strokeStyle = "rgba(255,255,255,0.06)";
    ctx.lineWidth = 1;
    roundRect(ctx, padding, y, contentWidth, groupHeight, 8);
    ctx.stroke();

    ctx.fillStyle = "#ffffff";
    ctx.font = "600 12px Inter, system-ui, sans-serif";
    ctx.fillText(group.homeTeam + " vs " + group.awayTeam, padding + 10, y + 18);
    ctx.fillStyle = "rgba(255,255,255,0.4)";
    ctx.font = "10px Inter, system-ui, sans-serif";
    ctx.fillText(group.competition, padding + 10, y + 34);

    let pickY = y + 44;
    for (const pick of group.picks) {
      ctx.fillStyle = "rgba(0,0,0,0.3)";
      roundRect(ctx, padding + 8, pickY, contentWidth - 16, 36, 4);
      ctx.fill();

      ctx.fillStyle = "rgba(255,255,255,0.4)";
      ctx.font = "bold 9px Inter, system-ui, sans-serif";
      ctx.fillText(pick.market.toUpperCase(), padding + 16, pickY + 14);

      ctx.fillStyle = "#ffffff";
      ctx.font = "500 11px Inter, system-ui, sans-serif";
      ctx.fillText(pick.pick, padding + 16, pickY + 28);

      const confColor = pick.confidence >= 70 ? "#00FFA3" : pick.confidence >= 45 ? "#FFB800" : "#EF4444";
      ctx.fillStyle = confColor;
      ctx.font = "bold 12px 'Roboto Mono', monospace";
      const confText = pick.confidence + "%";
      const confWidth = ctx.measureText(confText).width;
      ctx.fillText(confText, width - padding - 16 - confWidth, pickY + 22);

      pickY += 44;
    }

    y += groupHeight + 12;
  }

  ctx.strokeStyle = "rgba(255,255,255,0.1)";
  ctx.beginPath();
  ctx.moveTo(padding, y);
  ctx.lineTo(width - padding, y);
  ctx.stroke();
  y += 12;

  ctx.fillStyle = "rgba(255,255,255,0.5)";
  ctx.font = "11px Inter, system-ui, sans-serif";
  ctx.fillText(itemCount + " selections", padding, y + 12);

  const confColor2 = combinedConfidence >= 65 ? "#00FFA3" : combinedConfidence >= 45 ? "#FFB800" : "#EF4444";
  ctx.fillStyle = confColor2;
  ctx.font = "bold 14px 'Roboto Mono', monospace";
  const confText2 = combinedConfidence + "% confidence";
  const confWidth2 = ctx.measureText(confText2).width;
  ctx.fillText(confText2, width - padding - confWidth2, y + 12);
  y += 24;

  ctx.fillStyle = "rgba(255,255,255,0.2)";
  ctx.font = "8px Inter, system-ui, sans-serif";
  const dateText = "Generated by OddsAura - " + new Date().toLocaleDateString();
  const dateWidth = ctx.measureText(dateText).width;
  ctx.fillText(dateText, (width - dateWidth) / 2, y + 10);

  return canvas;
}

function roundRect(ctx: CanvasRenderingContext2D, x: number, y: number, w: number, h: number, r: number) {
  ctx.beginPath();
  ctx.moveTo(x + r, y);
  ctx.lineTo(x + w - r, y);
  ctx.quadraticCurveTo(x + w, y, x + w, y + r);
  ctx.lineTo(x + w, y + h - r);
  ctx.quadraticCurveTo(x + w, y + h, x + w - r, y + h);
  ctx.lineTo(x + r, y + h);
  ctx.quadraticCurveTo(x, y + h, x, y + h - r);
  ctx.lineTo(x, y + r);
  ctx.quadraticCurveTo(x, y, x + r, y);
  ctx.closePath();
}

export function BetSlip() {
  const { items, removeItem, clearAll, combinedConfidence, isOpen, setIsOpen } = useBetSlip();
  const [saving, setSaving] = useState(false);
  const [sharing, setSharing] = useState(false);
  const { toast } = useToast();

  const matchGroups = items.reduce((groups, item) => {
    const key = item.matchId;
    if (!groups[key]) {
      groups[key] = {
        matchId: item.matchId,
        homeTeam: item.homeTeam,
        awayTeam: item.awayTeam,
        competition: item.competition,
        picks: [],
      };
    }
    groups[key].picks.push(item.market);
    return groups;
  }, {} as Record<number, { matchId: number; homeTeam: string; awayTeam: string; competition: string; picks: typeof items[0]["market"][] }>);

  const groupedMatches = Object.values(matchGroups);

  const handleSaveImage = useCallback(async () => {
    setSaving(true);
    try {
      const canvas = drawPicksToCanvas(groupedMatches, items.length, combinedConfidence);
      const filename = `my-picks-${new Date().toISOString().split("T")[0]}.png`;

      try {
        const blob = await new Promise<Blob>((resolve, reject) => {
          canvas.toBlob(b => b ? resolve(b) : reject(new Error("toBlob failed")), "image/png");
        });

        if (navigator.share && /mobile|android|iphone/i.test(navigator.userAgent)) {
          const file = new File([blob], filename, { type: "image/png" });
          await navigator.share({ files: [file], title: "My Picks - OddsAura" });
        } else {
          const url = URL.createObjectURL(blob);
          const a = document.createElement("a");
          a.href = url;
          a.download = filename;
          document.body.appendChild(a);
          a.click();
          document.body.removeChild(a);
          setTimeout(() => URL.revokeObjectURL(url), 5000);
        }
      } catch {
        const dataUrl = canvas.toDataURL("image/png");
        const w = window.open();
        if (w) {
          w.document.write(`<img src="${dataUrl}" style="max-width:100%" />`);
          w.document.title = "My Picks - Right click to save";
        }
      }

      toast({
        title: "Picks saved!",
        description: "Your picks have been saved as an image.",
      });
    } catch (err) {
      console.error("Failed to export image:", err);
      toast({
        title: "Save failed",
        description: "Could not save image. Please try again.",
        variant: "destructive",
      });
    } finally {
      setSaving(false);
    }
  }, [groupedMatches, items.length, combinedConfidence, toast]);

  const copyToClipboard = async (text: string): Promise<boolean> => {
    try {
      await navigator.clipboard.writeText(text);
      return true;
    } catch {
      try {
        const textarea = document.createElement("textarea");
        textarea.value = text;
        textarea.style.position = "fixed";
        textarea.style.left = "-9999px";
        document.body.appendChild(textarea);
        textarea.select();
        document.execCommand("copy");
        document.body.removeChild(textarea);
        return true;
      } catch {
        return false;
      }
    }
  };

  const handleShare = useCallback(async () => {
    setSharing(true);
    try {
      const picks = items.map(item => ({
        matchId: item.matchId,
        homeTeam: item.homeTeam,
        awayTeam: item.awayTeam,
        competition: item.competition,
        market: item.market,
      }));
      const res = await apiRequest("POST", "/api/shared-picks", { picks });
      const data = await res.json();
      const url = `${window.location.origin}/shared/${data.shareCode}`;
      const copied = await copyToClipboard(url);
      toast({
        title: copied ? "Link copied!" : "Share link created!",
        description: copied ? "Share link has been copied to clipboard." : url,
      });
    } catch (err) {
      console.error("Share failed:", err);
      toast({
        title: "Share failed",
        description: "Could not create share link. Please try again.",
        variant: "destructive",
      });
    } finally {
      setSharing(false);
    }
  }, [items, toast]);

  if (items.length === 0) return null;

  if (!isOpen) {
    return (
      <button
        className="fixed bottom-4 right-4 z-50 flex items-center gap-2 px-3 py-2 rounded-full bg-[#00FFA3] text-black font-bold text-xs shadow-lg shadow-[#00FFA3]/20 transition-transform hover:scale-105 active:scale-95"
        onClick={() => setIsOpen(true)}
        data-testid="button-open-picks"
      >
        <Star className="w-3.5 h-3.5" />
        My Picks
        <Badge className="bg-black text-[#00FFA3] text-[10px] px-1.5 py-0 font-bold ml-0.5">
          {items.length}
        </Badge>
      </button>
    );
  }

  return (
    <div className="fixed bottom-4 right-4 z-50 w-80 max-w-[calc(100vw-2rem)] max-h-[80vh] flex flex-col" data-testid="my-picks-panel">
      <Card className="bg-[#0a1118] border border-[#00FFA3]/25 shadow-xl shadow-[#00FFA3]/5 overflow-hidden flex flex-col max-h-[80vh]">
        <button
          className="w-full flex items-center justify-between p-3 bg-[#00FFA3]/10 border-b border-[#00FFA3]/20 cursor-pointer"
          onClick={() => setIsOpen(false)}
          data-testid="button-toggle-picks"
        >
          <div className="flex items-center gap-2">
            <Star className="w-4 h-4 text-[#00FFA3]" />
            <span className="text-sm font-semibold text-white">My Picks</span>
            <Badge className="bg-[#00FFA3] text-black text-[10px] px-1.5 py-0 font-bold">
              {items.length}
            </Badge>
          </div>
          <X className="w-4 h-4 text-white/60" />
        </button>

        <ScrollArea className="flex-1 overflow-auto" style={{ maxHeight: "40vh" }}>
          <div className="p-3 space-y-3">
            {groupedMatches.map((group) => (
              <div key={group.matchId} className="bg-white/5 rounded-lg p-2.5 border border-white/8">
                <div className="flex items-center justify-between mb-2">
                  <div>
                    <p className="text-xs font-semibold text-white">{group.homeTeam} vs {group.awayTeam}</p>
                    <p className="text-[10px] text-white/50">{group.competition}</p>
                  </div>
                </div>
                <div className="space-y-1.5">
                  {group.picks.map((pick) => (
                    <div key={pick.market} className="flex items-center justify-between gap-2 bg-black/30 rounded px-2 py-1.5">
                      <div className="flex-1 min-w-0">
                        <p className="text-[10px] text-white/50 uppercase tracking-wider">{pick.market}</p>
                        <p className="text-xs font-medium text-white truncate">{pick.pick}</p>
                      </div>
                      <div className="flex items-center gap-2 flex-shrink-0">
                        <span className={`text-xs font-mono font-bold ${
                          pick.confidence >= 70 ? "text-[#00FFA3]" :
                          pick.confidence >= 45 ? "text-[#FFB800]" : "text-red-400"
                        }`}>{pick.confidence}%</span>
                        <button
                          onClick={() => removeItem(group.matchId, pick.market)}
                          className="text-white/30 hover:text-red-400 transition-colors"
                          data-testid={`button-remove-pick-${group.matchId}-${pick.market}`}
                        >
                          <X className="w-3.5 h-3.5" />
                        </button>
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            ))}
          </div>
        </ScrollArea>

        <div className="p-3 border-t border-white/10 bg-black/30 space-y-2">
          <div className="flex items-center justify-between">
            <span className="text-xs text-white/60">Selections</span>
            <span className="text-sm font-mono font-bold text-white">{items.length}</span>
          </div>
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-1">
              <TrendingUp className="w-3 h-3 text-[#00FFA3]" />
              <span className="text-xs text-white/60">Combined Confidence</span>
            </div>
            <span className={`text-sm font-mono font-bold ${
              combinedConfidence >= 65 ? "text-[#00FFA3]" :
              combinedConfidence >= 45 ? "text-[#FFB800]" : "text-red-400"
            }`}>{combinedConfidence}%</span>
          </div>
        </div>

        <div className="p-3 border-t border-white/10 space-y-2">
          <div className="flex gap-2">
            <Button
              size="sm"
              className="flex-1 bg-[#00FFA3] text-black text-xs gap-1 font-bold"
              onClick={handleSaveImage}
              disabled={saving}
              data-testid="button-save-picks-image"
            >
              {saving ? (
                <Loader2 className="w-3 h-3 animate-spin" />
              ) : (
                <Download className="w-3 h-3" />
              )}
              {saving ? "Saving..." : "Save Image"}
            </Button>
            <Button
              size="sm"
              className="flex-1 bg-white/10 text-white text-xs gap-1 font-bold hover:bg-white/15"
              onClick={handleShare}
              disabled={sharing}
              data-testid="button-share-picks"
            >
              {sharing ? (
                <Loader2 className="w-3 h-3 animate-spin" />
              ) : (
                <Share2 className="w-3 h-3" />
              )}
              {sharing ? "Sharing..." : "Share Link"}
            </Button>
          </div>
          <Button
            variant="ghost"
            size="sm"
            className="w-full text-red-400 text-xs gap-1"
            onClick={clearAll}
            data-testid="button-clear-picks"
          >
            <Trash2 className="w-3 h-3" />
            Clear All
          </Button>
        </div>
      </Card>
    </div>
  );
}
